# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-26 10:36
from __future__ import unicode_literals

from django.db import migrations, models
import django_hash_field


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_field', django_hash_field.HashField(db_index=True, max_length=16)),
                ('i', models.IntegerField()),
            ],
        ),
    ]
